// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlydqrrnaozmcxyxpvhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZseWRxcnJuYW96bWN4eXhwdmh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMTgwNTYsImV4cCI6MjA2OTU5NDA1Nn0.6AMywfseQy7OZmAgsuSRZB9RNCXsapCEL5do9DfaGfE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});